%YAML:1.0
aruco_bc_nmarkers: 15
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:983, corners:[ [ -290., -170., 0. ], [ -190., -170., 0. ], [
       -190., -70., 0. ], [ -290., -70., 0. ] ] }
   - { id:470, corners:[ [ -170., -170., 0. ], [ -70., -170., 0. ], [
       -70., -70., 0. ], [ -170., -70., 0. ] ] }
   - { id:822, corners:[ [ -50., -170., 0. ], [ 50., -170., 0. ], [ 50.,
       -70., 0. ], [ -50., -70., 0. ] ] }
   - { id:96, corners:[ [ 70., -170., 0. ], [ 170., -170., 0. ], [ 170.,
       -70., 0. ], [ 70., -70., 0. ] ] }
   - { id:436, corners:[ [ 190., -170., 0. ], [ 290., -170., 0. ], [
       290., -70., 0. ], [ 190., -70., 0. ] ] }
   - { id:447, corners:[ [ -290., -50., 0. ], [ -190., -50., 0. ], [
       -190., 50., 0. ], [ -290., 50., 0. ] ] }
   - { id:997, corners:[ [ -170., -50., 0. ], [ -70., -50., 0. ], [ -70.,
       50., 0. ], [ -170., 50., 0. ] ] }
   - { id:967, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50.,
       50., 0. ], [ -50., 50., 0. ] ] }
   - { id:38, corners:[ [ 70., -50., 0. ], [ 170., -50., 0. ], [ 170.,
       50., 0. ], [ 70., 50., 0. ] ] }
   - { id:288, corners:[ [ 190., -50., 0. ], [ 290., -50., 0. ], [ 290.,
       50., 0. ], [ 190., 50., 0. ] ] }
   - { id:425, corners:[ [ -290., 70., 0. ], [ -190., 70., 0. ], [ -190.,
       170., 0. ], [ -290., 170., 0. ] ] }
   - { id:894, corners:[ [ -170., 70., 0. ], [ -70., 70., 0. ], [ -70.,
       170., 0. ], [ -170., 170., 0. ] ] }
   - { id:948, corners:[ [ -50., 70., 0. ], [ 50., 70., 0. ], [ 50.,
       170., 0. ], [ -50., 170., 0. ] ] }
   - { id:501, corners:[ [ 70., 70., 0. ], [ 170., 70., 0. ], [ 170.,
       170., 0. ], [ 70., 170., 0. ] ] }
   - { id:184, corners:[ [ 190., 70., 0. ], [ 290., 70., 0. ], [ 290.,
       170., 0. ], [ 190., 170., 0. ] ] }
